const defaultInitialState = {
  recipes: [
    {
      idPk: '1',
      name: 'French Toast Casserole',
      directions: [{title: null, steps:['Slice the bread 1 inch thick and lay in a 9\'x13\' casserole. Mix the other ingredients, except the butter, and pour over the bread.','Cover with foil and refrigerate 4-36 hours.','Dot with butter and bake 45-50 minutes at 350\'. Let it set for 5 minutes before serving.']}],
      description: null,
      ingredients: [{title:null,'ingredients':['1 (10in) loaf Italian or French bred: not sliced','8 large Eggs','4tsp Sugar','3 cups Milk','1tsp Vanilla','3/4tsp Salt','2tbsp Butter, cut into small pieces']}],
      authorFk: '1',
      tags: [{category: 'Cooking Style', label: 'Make Ahead'},{category: 'Difficulty', label: 'Easy'},{category: 'Ethnicity', label: 'American'},{category: 'Section', label: 'Lunch & Brunch'},{category: 'Dietary Preference', label: 'Vegetarian'}],
      additionalAttributes: {
        note: null,
        cookTime: null,
        serves: null,
        author:'Connie',
      },
    },
    {
      idPk: '2',
      name: 'Cheese Bread Knots',
      directions: [{title: null, steps:['In a large mixing bowl combine 2 cups flour and yeast. In a saucepan, heat the milk, cheese, sugar, butter, and salt until just 115-120\' and the butter and cheese are almost melted. Stir constantly. Add to the flour mixture and add the egg.','Beat at low speed 1/2 minute, scraping the sides. Beat 3 minutes at high. Stir in as much of the remaining 3 1/2 cups flour as you can mix in with a spoon.','Turn our onto a lightly floured surface. Knead in enough of the remaining flour to make a soft dough. Knead 8 minutes. Shape into a ball, cover with plastic wrap or a towel and leave for about 1 1/2 hours or until double.','Pound the dough down and turn our onto a lightly floured surface. Divide dough into 4 equal pieces. Shape each into a ball. Cover with a towel and let it rest for 10 minutes.','Remove one ball at a time from the towel and roll it into a 12\'x6\' rectangle. Cut crosswise into 6 1-inch strips. Tie each strip into a loose knot. Place 2-3 inches apart on a greased sheet. Let rise covered 40 minutes.','Brush with melted butter. Bake at 375\' for 10-12 minutes.']}],
      description: null,
      ingredients: [{title:null,'ingredients':['5-5 1/2 cups Flour','2 packages Yeast _OR_ 2tbsp Yeast','2 cups Milk','1 1/2 cups (6oz) Swiss Cheese, cubed','1/2 cup Sugar','1/4 cup Butter','1tbsp Salt','1 Egg']}],
      authorFk: '1',
      tags: [{category: 'Difficulty', label: 'Hard'},{category: 'Dietary Preference', label: 'Vegetarian'},{category: 'Section', label: 'Bread'},{category: 'Ethnicity', label: 'American'}],
      additionalAttributes: {
        note: null,
        cookTime: null,
        serves: null,
        author: 'Dawn',
      },
    },
    {
      idPk: '3',
      name:'Frosted Cauliflower',
      directions: [{title: null, steps:['Remove the leaves and woody base of the cauliflower. Wash and cook the cauliflower 12-15 minutes covered in boiling water, or steam.','Place it in a shallow baking dish and sprinkle with salt. Mix the mayonnaise and mustard and spread over the cauliflower with the cheese.','Bake at 375\' for about 10 minutes.']}],
      description: null,
      ingredients: [{title:null,'ingredients':['1 medium head Cauliflower','Salt','1/2 cup Mayonnaise','2tsp prepared Mustard','3/4 cup Shredded Sharp Cheddar Cheese, or more']}],
      authorFk: '1',
      tags: [{category: 'Ethnicity', label: 'American'},{category: 'Difficulty', label: 'Easy'},{category: 'Dietary Preference', label: 'Vegetarian'},{category: 'Dietary Preference', label: 'Gluten Free'},{category: 'Section', label: 'Vegetable'}],
      additionalAttributes: {
        note: null,
        cookTime: null,
        serves: null,
        author:'Mary Kay',
      },
    },
    {
      idPk: '4',
      name:'Irish Soda Bread II',
      directions: [{title: null, steps:['Mix dry ingredients together. Mix wet ingredients together. Mix all ingredients together with an electric mixer for about 5 minutes until well blended.','Form into a ball and flatten in a round lightly greased cake pan. Cut a cross on top of the dough with a knife.','Bake at 350\' for 1 hour.']}],
      description: 'Another, differentv ersion.',
      ingredients:[{title:null,'ingredients':['4 cups Flour','1 1/2tsp Baking Soda','1tsp Salt','1 cup White Raisins','3/4 cup Sugar','1 cup Buttermilk','2 Eggs','2tbsp Butter, melted']}],
      authorFk: '1',
      tags: [{category: 'Difficulty', label: 'Easy'},{category: 'Section', label: 'Bread'},{category: 'Ethnicity', label: 'American'},{category: 'Dietary Preference', label: 'Vegetarian'}],
      additionalAttributes: {
        note: null,
        cookTime: null,
        serves: null,
        author:'Dawn',
      },
    }
  ],
  recipeForm: {
    open: false,
    saving: false,
    author: '',
    description: '',
    note: '',
    title: '',
    cookTime: '',
    serves: '',
    ingredients: [{title: '',ingredients:[]}],
    directions: [{title: '', steps:[]}],
    tags: [],
  },
  filters:{
    recipes:[
      { category:  'Section',  label: ' Lunch & Brunch' },
      {  label:  'Medium', category:  'Difficulty' },
    ]
  },
  quotes:[
    {author: 'English Proverb', quote: 'Don\'t put all your eggs in one basket.' },
    {author: 'Mae West', quote: 'I never worry about diets. The only carrots that interest me are the number you get in a diamond.' },
    {author: 'Old Wives Tale', quote: 'Feed a cold; starve a fever.' },
    {author: 'Julia Child', quote: 'Buy olive oil for its taste, not its virginity.' },
  ],
  search: { recipes: '' },
  tags:[
    {category: 'Cooking Style','listOrder':1, label: 'BBQ & Grilling','checked':false, numberOfRecipes: 0 },
    {category: 'Cooking Style','listOrder':2, label: 'Casserole','checked':false, numberOfRecipes: 0 },
    {category: 'Cooking Style','listOrder':3, label: 'Make Ahead','checked':false, numberOfRecipes: 2 },
    {category: 'Cooking Style','listOrder':5, label: 'Quick & Easy','checked':false, numberOfRecipes: 0 },
    {category: 'Cooking Style','listOrder':4, label: 'Slow Cooker','checked':false, numberOfRecipes: 0 },
    {category: 'Difficulty','listOrder':1, label: 'Easy','checked':false, numberOfRecipes: 19 },
    {category: 'Difficulty','listOrder':3, label: 'Hard','checked':false, numberOfRecipes: 0 },
    {category: 'Difficulty','listOrder':2, label: 'Medium','checked':true, numberOfRecipes: 7 },
    {category: 'Dietary Preference','listOrder':1, label: 'Dairy Free','checked':false, numberOfRecipes: 1 },
    {category: 'Dietary Preference','listOrder':2, label: 'Gluten Free','checked':false, numberOfRecipes: 0 },
    {category: 'Dietary Preference','listOrder':3, label: 'Vegetarian','checked':false, numberOfRecipes: 4 },
    {category: 'Ethnicity','listOrder':1, label: 'American','checked':false, numberOfRecipes: 7 },
    {category: 'Ethnicity','listOrder':2, label: 'Asian','checked':false, numberOfRecipes: 0 },
    {category: 'Ethnicity','listOrder':3, label: 'French','checked':false, numberOfRecipes: 0 },
    {category: 'Ethnicity','listOrder':4, label: 'German','checked':false, numberOfRecipes: 0 },
    {category: 'Ethnicity','listOrder':5, label: 'Italian','checked':false, numberOfRecipes: 1 },
    {category: 'Ethnicity','listOrder':6, label: 'Mexican','checked':false, numberOfRecipes: 0 },
    {category: 'Section','listOrder':1, label: 'Appetizer','checked':false, numberOfRecipes: 6 },
    {category: 'Section','listOrder':14, label: 'Bits & Pieces','checked':false, numberOfRecipes: 0 },
    {category: 'Section','listOrder':4, label: 'Bread','checked':false, numberOfRecipes: 7 },
    {category: 'Section','listOrder':11, label: 'Cakes','checked':false, numberOfRecipes: 0 },
    {category: 'Section','listOrder':13, label: 'Candies & Sweets','checked':false, numberOfRecipes: 0 },
    {category: 'Section','listOrder':10, label: 'Cookies & Bars','checked':false, numberOfRecipes: 0 },
    {category: 'Section','listOrder':9, label: 'Desserts','checked':false, numberOfRecipes: 1 },
    {category: 'Section','listOrder':5, label: 'Lunch & Brunch','checked':true, numberOfRecipes: 7 },
    {category: 'Section','listOrder':8, label: 'Meat & Fish','checked':false, numberOfRecipes: 1 },
    {category: 'Section','listOrder':12, label: 'Pies','checked':false, numberOfRecipes: 0 },
    {category: 'Section','listOrder':7, label: 'Poultry','checked':false, numberOfRecipes: 1 },
    {category: 'Section','listOrder':3, label: 'Salad','checked':false, numberOfRecipes: 14 },
    {category: 'Section','listOrder':2, label: 'Soup','checked':false, numberOfRecipes: 5 },
    {category: 'Section','listOrder':6, label: 'Vegetable','checked':false, numberOfRecipes: 3 },
  ],
  sections: [
    { name: 'first section', listOrder: 1 },
    { name: 'second section', listOrder: 2 },
  ],
  user:{
    authenticating:false,
    activeUser: {
      idPk: '1',
      favorites:['1','2'],
      legalFirstName: 'Joseph',
      legalMiddleName: 'Martin',
      legalLastName: 'Lissner',
      isAdmin: true,
    },
    users:[{
      idPk: '1',
      preferredName: 'Joseph',
      legalMiddleName: 'Martin',
      legalLastName: 'Lissner',
      preferredName: 'Joe',
      favorites: ['1','2'],
      idAdmin: true,
    }, {
      idPk: '2',
      preferredName: 'Connie',
      legalMiddleName: null,
      legalLastName: 'Kelly',
      preferredName: null,
      favorites: ['1','2'],
      idAdmin: false,
    }],
  },
}

export default defaultInitialState;